# Generated by Django 4.2.28 on 2026-03-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attraction_og_image_attraction_og_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('airport', 'Airport'), ('train_station', 'Train Station'), ('bus_terminal', 'Bus Terminal'), ('major_city', 'Major City / Town'), ('port', 'Port / Ferry Terminal'), ('ferry', 'Ferry Stop')], max_length=20)),
                ('name', models.CharField(help_text='e.g., Kilimanjaro International Airport', max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=7)),
                ('travel_time_minutes', models.IntegerField(blank=True, help_text='Approximate travel time in minutes', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional info, transport options, notes')),
                ('is_recommended', models.BooleanField(default=False, help_text='Recommended route/facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_facilities', to='attractions.attraction')),
            ],
            options={
                'verbose_name': 'Nearest Transport',
                'verbose_name_plural': 'Nearest Transports',
                'ordering': ['distance_km'],
            },
        ),
    ]
