# Generated by Django 4.2.7 on 2026-02-15 15:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('mountain', 'Mountain'), ('beach', 'Beach'), ('wildlife', 'Wildlife Safari'), ('cultural', 'Cultural Site'), ('historical', 'Historical Site'), ('adventure', 'Adventure Activity'), ('national_park', 'National Park'), ('island', 'Island'), ('waterfall', 'Waterfall'), ('lake', 'Lake'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.IntegerField(blank=True, help_text='Altitude in meters', null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('access_info', models.TextField(help_text='How to reach this attraction')),
                ('nearest_airport', models.CharField(blank=True, max_length=100)),
                ('distance_from_airport', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=6, null=True)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('seasonal_availability', models.TextField(help_text='When is this attraction accessible?')),
                ('estimated_duration', models.CharField(help_text='e.g., 5-7 days, 2 hours', max_length=100)),
                ('entrance_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in USD', max_digits=10, null=True)),
                ('requires_guide', models.BooleanField(default=False)),
                ('requires_permit', models.BooleanField(default=False)),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attractions', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='regions.region')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='attractions.attraction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category'], name='attractions_categor_2f4c97_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['region'], name='attractions_region__c03a58_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['difficulty_level'], name='attractions_difficu_67908a_idx'),
        ),
    ]
